### ISSUE TITLE
nibbles: out: callProcess: posix_spawnp: does not exist (No such file or directory)

### ISSUE THREAD

**Issue by xigoi** [darrenks/nibbles#2]
I installed Nibbles on Manjaro WSL using the recommended instructions (with `ghcup`). When I run the executable and enter a Nibbles program, it outputs the program size as expected and then the following error:

```
nibbles: out: callProcess: posix_spawnp: does not exist (No such file or directory)
```

**Comment by darrenks** [comment]
Hi xigoi, I'm not at all familiar with Manjaro WSL but I think we can figure this out. It sounds like it is having trouble running a process which could either be compiling the generated HS code, or running the compiled executable. 

Can you check if it generated an executable called "out"?

If so, then can you try just running that on its own (I'd expect it to work).

If not, can you see if out.hs exists and contains a valid Haskell program?

If so you can probably compile that with "ghc -O". (and then run "out")

Even if you get it working with one of these workarounds, please let me know so we can try to fix it properly.

Thanks!
Darren

**Comment by xigoi** [comment]
Thank you for the answer! It does produce an executable `./out`, which works normally, so this is an acceptable workaround.

Also, when I compile a program with arguments (for example `nibbles program.nbl '"foo"'` and try to use `$` in the program to access the argument, running `./out` gives the error `out: Prelude.!!: index too large`. Do you have an idea why this could be?

**Comment by xigoi** [comment]
Okay, so the latter problem can be solved by giving the arguments both to the compiler and the executable. I wrongly assumed the compiler would “capture” them.

**Comment by darrenks** [comment]
Thanks. Would you mind seeing if changing `callProcess "out" args` in nibbles.hs to `callProcess "./out" args` fixes that original problem for you?

You are correct about needing to pass the args during both compile time and run time (which would be done automatically for you if the first issue hadn't happened). I'll improve that error message though.

**Comment by xigoi** [comment]
I made the change you described and it's working! Maybe your system has `.` in `$PATH` so it wasn't needed for you?

**Comment by darrenks** [comment]
That's correct. Thanks again for reporting these issues!

**Comment by darrenks** [comment]
(latest unstable version has these fixes)
